// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"parentId":"@@/global-layout","id":"1"},"2":{"path":"/","redirect":"/vote","parentId":"1","id":"2"},"3":{"path":"/vote","parentId":"1","id":"3"},"4":{"path":"/alignment","parentId":"1","id":"4"},"5":{"path":"/governance/:subspaceId","parentId":"1","id":"5"},"6":{"path":"/create-subspace","parentId":"1","id":"6"},"7":{"path":"/causalitygraph","parentId":"1","id":"7"},"8":{"path":"/model","parentId":"1","id":"8"},"9":{"path":"/model/create","parentId":"1","id":"9"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__vote__index" */'@/pages/vote/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__alignment__index" */'@/pages/alignment/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__governance__index" */'@/pages/governance/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__create-subspace__index" */'@/pages/create-subspace/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__causality_graph__index" */'@/pages/causality_graph/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__model__welcome__index" */'@/pages/model/welcome/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__model__create__index" */'@/pages/model/create/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/home/litterpigger/hetu/causality/demo_one/src/layouts/index.tsx')),
},
  };
}
